[server]
fileWatcherType = "poll"
#enableCORS = false
[ui]
hideTopBar = true
[client]
showSidebarNavigation = false
toolbarMode = 'minimal'
[theme] #
backgroundColor = '#fcf9f9' 
#[browser]
#gatherUsageStats = false
